// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

//template:end imports

//template:begin types
type ImageFromUrl struct {
	Id              types.String `tfsdk:"id"`
	ApplicationType types.String `tfsdk:"application_type"`
	Family          types.String `tfsdk:"family"`
	SourceUrl       types.String `tfsdk:"source_url"`
	Name            types.String `tfsdk:"name"`
	Vendor          types.String `tfsdk:"vendor"`
	ThirdParty      types.Bool   `tfsdk:"third_party"`
}

//template:end types

//template:begin getPath
func (data ImageFromUrl) getPath() string {
	return "/dna/intent/api/v1/image/importation/source/url#"
}

//template:end getPath

//template:begin toBody
func (data ImageFromUrl) toBody(ctx context.Context, state ImageFromUrl) string {
	body := ""
	if !data.ApplicationType.IsNull() {
		body, _ = sjson.Set(body, "applicationType", data.ApplicationType.ValueString())
	}
	if !data.Family.IsNull() {
		body, _ = sjson.Set(body, "0.imageFamily", data.Family.ValueString())
	}
	if !data.SourceUrl.IsNull() {
		body, _ = sjson.Set(body, "0.sourceURL", data.SourceUrl.ValueString())
	}
	if !data.Vendor.IsNull() {
		body, _ = sjson.Set(body, "0.vendor", data.Vendor.ValueString())
	}
	if !data.ThirdParty.IsNull() {
		body, _ = sjson.Set(body, "0.thirdParty", data.ThirdParty.ValueBool())
	}
	return body
}

//template:end toBody

//template:begin fromBody
func (data *ImageFromUrl) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("response.0.applicationType"); value.Exists() {
		data.ApplicationType = types.StringValue(value.String())
	} else {
		data.ApplicationType = types.StringNull()
	}
	if value := res.Get("response.0.family"); value.Exists() {
		data.Family = types.StringValue(value.String())
	} else {
		data.Family = types.StringNull()
	}
	if value := res.Get("response.0.vendor"); value.Exists() {
		data.Vendor = types.StringValue(value.String())
	} else {
		data.Vendor = types.StringNull()
	}
}

//template:end fromBody

//template:begin updateFromBody
func (data *ImageFromUrl) updateFromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("response.0.applicationType"); value.Exists() && !data.ApplicationType.IsNull() {
		data.ApplicationType = types.StringValue(value.String())
	} else {
		data.ApplicationType = types.StringNull()
	}
	if value := res.Get("response.0.family"); value.Exists() && !data.Family.IsNull() {
		data.Family = types.StringValue(value.String())
	} else {
		data.Family = types.StringNull()
	}
	if value := res.Get("response.0.vendor"); value.Exists() && !data.Vendor.IsNull() {
		data.Vendor = types.StringValue(value.String())
	} else {
		data.Vendor = types.StringNull()
	}
}

//template:end updateFromBody
