// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

//template:end imports

//template:begin types
type Discovery struct {
	Id            types.String `tfsdk:"id"`
	CdpLevel      types.Int64  `tfsdk:"cdp_level"`
	DiscoveryType types.String `tfsdk:"discovery_type"`
}

//template:end types

//template:begin getPath
func (data Discovery) getPath() string {
	return "/dna/intent/api/v1/discovery"
}

//template:end getPath

//template:begin toBody
func (data Discovery) toBody(ctx context.Context, state Discovery) string {
	body := ""
	if !data.CdpLevel.IsNull() {
		body, _ = sjson.Set(body, "request.cdpLevel", data.CdpLevel.ValueInt64())
	}
	if !data.DiscoveryType.IsNull() {
		body, _ = sjson.Set(body, "request.discoveryType", data.DiscoveryType.ValueString())
	}
	return body
}

//template:end toBody

//template:begin fromBody
func (data *Discovery) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("request.cdpLevel"); value.Exists() {
		data.CdpLevel = types.Int64Value(value.Int())
	} else {
		data.CdpLevel = types.Int64Null()
	}
	if value := res.Get("request.discoveryType"); value.Exists() {
		data.DiscoveryType = types.StringValue(value.String())
	} else {
		data.DiscoveryType = types.StringNull()
	}
}

//template:end fromBody

//template:begin updateFromBody
func (data *Discovery) updateFromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("request.cdpLevel"); value.Exists() && !data.CdpLevel.IsNull() {
		data.CdpLevel = types.Int64Value(value.Int())
	} else {
		data.CdpLevel = types.Int64Null()
	}
	if value := res.Get("request.discoveryType"); value.Exists() && !data.DiscoveryType.IsNull() {
		data.DiscoveryType = types.StringValue(value.String())
	} else {
		data.DiscoveryType = types.StringNull()
	}
}

//template:end updateFromBody
